### ISSUE TITLE
Fail to Import

### ISSUE THREAD

**Issue by DeeJayhX** [KeyWeeUsr/KV-for-NotepadPP#1]
Importing the XML file into the current version of Notepad++ leads to a simply dialog saying "Fail to Import." I'm not surprised as there is a three year difference, just wasn't sure if you were still maintaining this and maybe just hadn't uploaded to github.

**Comment by KeyWeeUsr** [comment]
I haven't used this one for a while, but I will take a look if there are problems with importing.

**Comment by DeeJayhX** [comment]
There are no issues. I'm a complete moron or GitHub is trolling me. I copy and pasted the code into notepad++ and saved the xml myself, imported fine. I dont know what downloaded from github when I tried to save it, but it wasn't correct. The XML is still working beautifully. Thank you for your work!

**Comment by KeyWeeUsr** [comment]
No worries, happened to me once or twice. I'm glad it still helps someone. :)

**Comment by CliffBramlett** [comment]
Something still seems to be an issue though. I'm getting the same error on v7.6.3. "Fail to import" after choosing Language > Define your language > Import > KVLang.xml

**Comment by DeeJayhX** [comment]
> Something still seems to be an issue though. I'm getting the same error on v7.6.3. "Fail to import" after choosing Language > Define your language > Import > KVLang.xml

Guaranteed you're messing up the same way I did. Copy and paste the code from the xml o
into a text editor yourself and save it that way. Then import that so
Xml
